[workspace]
members = [
  "vmlinux",
  "libbpf-cargo",
  "libbpf-rs",
  "examples/bpf_query",
  "examples/capable",
  "examples/runqslower",
  "examples/tc_port_whitelist",
  "examples/tcp_ca",
  "examples/tproxy",
]
resolver = "2"

[patch.crates-io]
libbpf-sys = { git = "https://github.com/libbpf/libbpf-sys.git", rev = "75042c653ee956b8c262e41ca4bcfcb0e2c461a1" }
