name: Audit

on:
  pull_request:
    # Runs when Cargo files are updated in a PR.
    paths: 
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    # Runs every Sunday at midnight.
    - cron: 0 0 * * 0

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
