name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install -y clang-9 libelf-dev
    - name: Symlink clang
      run: sudo ln -s /usr/bin/clang-9 /bin/clang
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      # Skip tests that require BTF built into kernel
      run: cargo test --verbose -- --skip test_object
    - name: Run rustfmt
      run: cargo fmt -- --check
