name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Please adjust README and rust-version field in Cargo.toml files when
        # bumping version.
        rust: [stable, 1.59.0, nightly]
    steps:
    - name: "Set environmental variables"
      shell: bash
      run: |
        RUST_BACKTRACE_nightly='1'
        CFLAGS_nightly='-fsanitize=leak'
        CXXFLAGS_nightly='-fsanitize=leak'
        RUSTFLAGS_nightly='-Zsanitizer=leak'

        # A function for defining a variable conditional on the toolchain in
        # use.
        tc_var() {
          # Replace any dots in the toolchain name with underscores. Necessary
          # due to shell imposed variable naming restrictions.
          var="${1}_$(echo ${{ matrix.rust }} | tr . _)"
          echo "${1}=${!var}" >> ${GITHUB_ENV}
        }

        tc_var RUST_BACKTRACE
        tc_var RUSTFLAGS
        tc_var CFLAGS
        tc_var CXXFLAGS
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
        override: true
    - name: Install deps
      run: sudo apt-get install -y clang-14 libelf-dev zlib1g-dev
    - name: Symlink clang
      run: sudo rm -f /bin/clang && sudo ln -s /usr/bin/clang-14 /bin/clang
    - name: Build
      run: cargo build --verbose --workspace --exclude runqslower
    - name: Build capable example with static libelf and libz
      run: RUSTFLAGS="$RUSTFLAGS -L /usr/lib/x86_64-linux-gnu" cargo b --package capable --features=static
    - name: Run tests
      # Skip BTF tests which require sudo
      run: cargo test --verbose --workspace --exclude runqslower -- --skip test_object --skip test_tc
    - name: Run BTF tests
      run: cd libbpf-rs && cargo test --verbose -- test_object test_tc
    - if: ${{ matrix.rust != 'nightly' }}
      name: Run rustfmt
      run: cargo fmt --package libbpf-cargo libbpf-rs -- --check
    - if: ${{ matrix.rust != 'nightly' }}
      name: Run clippy
      run: cargo clippy --tests -- -D warnings
    - if: ${{ matrix.rust != 'nightly' }}
      name: Check documentation
      env:
        RUSTDOCFLAGS: '-D warnings'
      run: cargo doc --no-deps
